name: Elixir CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        runner: [self-hosted]
        os: [Linux, macOS]
        arch: [X64, ARM64]
        erlang-version: ["latest"]
        elixir-version: ["latest"]
    runs-on: ${{ matrix.runner }} ${{ matrix.os }} ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Erlang with asdf
      run: asdf install erlang ${{ matrix.erlang-version }}
    - name: Set up Erlang with asdf
      run: asdf local erlang ${{ matrix.erlang-version }}
    - name: Install Elixir with asdf
      run: asdf install elixir ${{ matrix.elixir-version }}
    - name: Set up Elixir with asdf
      run: asdf local elixir ${{ matrix.elixir-version }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ runner.arch }}-${{ runner.elixir-version }}-${{ runner.erlang-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-${{ runner.elixir-version }}-${{ runner.erlang-version }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
